export * from './header'
export * from './moviesList'
export * from './moviesListCard'
export * from './posterPreview'
export * from './movieInfo'
export * from './genreBadge'
export * from './userInfo'
export * from './Photo'
export * from './GenresInfo'
export * from './movieByIdDetaills'
export * from './cast'

